# Data Mining - Lab - 2

#  Numpy  &  Perform Data Exploration with Pandas
VIVEK SUDANI 23010101260

-------------------------------------------------------------------------------
## Numpy

1) NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing.<br>
2) It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.<br>
3) NumPy is highly optimized and written in C, making it much faster than using regular Python lists for numerical operations.<br>
4) It serves as the foundation for many other Python libraries in data science and machine learning, like pandas, TensorFlow, and scikit-learn.<br>
5) With features like broadcasting, vectorization, and integration with C/C++ code, NumPy allows for cleaner and faster code in numerical computations.<br>



### Step 1. Import the Numpy library

In [46]:
import numpy as np



### Step 2. Create a 1D array of numbers

In [47]:
arr2a = np.array([1,2,3,4])
print(arr2a)

[1 2 3 4]


In [48]:
arr = np.arange(11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [49]:
arr2 = np.arange(5,15)
print(arr2)

[ 5  6  7  8  9 10 11 12 13 14]


### Step 3. Reshape 1D to 2D Array

In [50]:
arr3 = np.arange(12,24).reshape(3,4)
print(arr3)

type(arr3) #array data type
arr3.dtype #data type of elements in array
arr3.size #size of array
arr3.ndim #dimention of array

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


2

In [51]:
arr3a = np.arange(11).reshape(12)
print(arr3a)

ValueError: cannot reshape array of size 11 into shape (12,)

### Step 4. Create a Linspace array

In [52]:
arr4 = np.linspace(0,5,20)
print(arr4)
print(arr4.dtype)

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
float64


### Step 5. Create a Random Numbered Array

In [53]:
#random no is beteen 0 and 1
arr5 = np.random.rand(5)
print(arr5)

[0.98389193 0.61572273 0.77580162 0.47753286 0.98955474]


In [54]:
arr5a = np.random.rand(5,10)
print(arr5a)

[[0.67009657 0.43291892 0.20560486 0.22759044 0.50925555 0.93525581
  0.73967754 0.0375468  0.05696406 0.23976802]
 [0.12949259 0.95475137 0.14802085 0.54382554 0.39660977 0.28773468
  0.14466139 0.09051567 0.30842042 0.64254812]
 [0.15748595 0.79987808 0.98836235 0.80024071 0.2283841  0.28483422
  0.26567091 0.68517765 0.54123405 0.23459615]
 [0.44051434 0.25452911 0.74942238 0.47145902 0.14811573 0.54249739
  0.62533296 0.48740294 0.18792976 0.2599996 ]
 [0.02132557 0.95762502 0.10466908 0.3765624  0.03839122 0.30706053
  0.96778262 0.07276518 0.69794765 0.43856935]]


### Step 6. Create a Random Integer Array

In [55]:
arr6 = np.random.randint(1,100,size = 10)
print(arr6)

[22 35 63 34 73 18 61 91  1 54]


### Step 7. Create a 1D Array and get Max,Min,ArgMax,ArgMin

In [56]:
arr7 = np.random.randint(1,100,size = 10)
print(arr7)
print(arr7.min())
print(arr7.max())

[10 92 42 27 81  4 77 33 27  3]
3
92


In [57]:
arr7 = np.random.randint(1,100,size = 10)
print(arr7)
print(arr7.argmin()) #returns the index (position) of the smallest value in an array
print(arr7.argmax()) #returns the index (position) of the largest value in an array

[49  2 61  9 31 29 47 44 56 44]
1
2


### Step 8. Indexing in 1D Array

In [58]:
arr8 = np.arange(10)
print(arr8)
print(arr8[1])

[0 1 2 3 4 5 6 7 8 9]
1


### Step 9. Indexing in 2D Array

In [59]:
arr8a = np.arange(10,19).reshape(3,3)
print(arr8a)
print(arr8a[0][0])

[[10 11 12]
 [13 14 15]
 [16 17 18]]
10


### Step 10. Conditional Selection

In [60]:
arr10 = np.arange(1,10)
print(arr10)
print(arr10[arr10 > 5])

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


### 🔥You did it! 10 exercises down — you're on fire! 🔥

## Pandas



### Step 1. Import the necessary libraries

In [61]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

In [62]:
df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep="|")

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [63]:
users = df

### Step 4. See the first 25 entries

In [64]:
users.head(25)

user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

### Step 5. See the last 10 entries

In [65]:
users.tail(10)


user_id  age gender     occupation zip_code
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [66]:
users.shape[0]

943

### Step 7. What is the number of columns in the dataset?

In [67]:
users.shape[1]

5

### Step 8. Print the name of all the columns.

In [68]:
users.columns

Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [69]:
users.index

RangeIndex(start=0, stop=943, step=1)

### Step 10. What is the data type of each column?

In [70]:
users.dtypes

user_id        int64
age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column

In [71]:
users["occupation"]

0         technician
1              other
2             writer
3         technician
4              other
           ...      
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [72]:
users['occupation'].nunique()

21

### Step 13. What is the most frequent occupation?

In [73]:
users.occupation.value_counts().head(1)

occupation
student    196
Name: count, dtype: int64

### Step 14. Summarize the DataFrame.

In [74]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   user_id     943 non-null    int64 
 1   age         943 non-null    int64 
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip_code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB


In [75]:
users.describe()

user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

### Step 15. Summarize all the columns

In [76]:
users.describe(include = "all" )

user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [77]:
users["occupation"].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [78]:
users["occupation"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 943 entries, 0 to 942
Series name: occupation
Non-Null Count  Dtype 
--------------  ----- 
943 non-null    object
dtypes: object(1)
memory usage: 7.5+ KB


### Step 17. What is the mean age of users?

In [79]:
users["age"].mean()

34.05196182396607

### Step 18. What is the age with least occurrence?

In [80]:
users["age"].value_counts().tail()

age
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64

### You're not just learning, you're mastering it. Keep aiming higher! 🚀